### ISSUE TITLE
Separate Groups

### ISSUE THREAD

**Issue by runahue** [dm5xx/UltraSwitch#1]
Hello friend:

You can separate "groups" on  ultraswitch_content_v1.js and this is GREAT.
But... Using groups... Can we set a Default per group?
Imagine a group being used to switch a 80 meter antenna coil.
You must always have one ON... When you power ultraswitch no one is ON on a Group.

Also: On web access... can we separate groups ?
And ... Can we add names to the top of groups?

80m Coil, 160m Coil, etc...

Thank's a lot.

You are doing a GREAT Job.

**Comment by dm5xx** [comment]
Hello runahue. Thanks for your replay. This all can be done by yourself if you are using your own webserver and some programming. im planning to create a node.js server for amateur radio dashboard views, but this will take some time.
if you want to have some more stuff, see my other projet called mega_webswitch. its much much more complex to setup, but there you get some deeper . 
The ultraswitch is following a principle "keep is simple stupid" - KISS. This means, there should be no logic in the device itself. Logic should go somwhere else in ne middle of the user and the device (in this case a proxy webserver). 
The experience from mega_webswitch was, that in 95% of all cases, nobody used grouing and the higher level stuff, but there have been a lot of support calls, because of the more complex setup. So this is why i change to a very common and useful architecture principle called KISS + some RESTful API, everybpdy can easily use.

"You must always have one ON... When you power ultraswitch no one is ON on a Group." => you can achieve this by changing the state in the sketch or call the right relays while startup

"can we separate groups" => you mean more space between 2 buttons of different groups? If so, yes, you can using some javascript/jquery and css. This is possible since everything can be changed.

"Can we add neames to the top of the groups" => see answer above :)

Thanks for using ultraswitch. 
Mike.

**Comment by runahue** [comment]
Thank's for your answer.

How is the Status sintax on ultraswitch_content_v1.js ?

**Comment by dm5xx** [comment]
If you need some help => dm5xx@gmx.de

**Comment by dm5xx** [comment]
x
